name: Go CI

on: push

jobs:
#    build-and-test:
    hello-world:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: '1.22'

            - name: Install dependencies
              run: go mod download

            - name: Run hello
              run: go run main.go

#            - name: Run tests
#              run: go test -v ./...